name: Build JARVIS iOS App

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Install Dependencies (if needed)
        run: |
          cd JARVIS
          if [ -f "Podfile" ]; then
            pod install
          fi

      - name: Build IPA
        run: |
          if [ -f "JARVIS.xcworkspace" ]; then
            xcodebuild -workspace JARVIS.xcworkspace \
                       -scheme JARVIS \
                       -sdk iphoneos \
                       -configuration Release \
                       archive -archivePath JARVIS.xcarchive
          else
            xcodebuild -project JARVIS.xcodeproj \
                       -scheme JARVIS \
                       -sdk iphoneos \
                       -configuration Release \
                       archive -archivePath JARVIS.xcarchive
          fi

      - name: Export IPA
        run: |
          mkdir -p output
          xcodebuild -exportArchive \
                     -archivePath JARVIS.xcarchive \
                     -exportOptionsPlist ExportOptions.plist \
                     -exportPath output \
                     -allowProvisioningUpdates

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: JARVIS-IPA
          path: output/
