name: Build JARVIS iOS App

on: [push]

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Xcode
        run: sudo xcode-select --switch /Applications/Xcode.app/Contents/Developer

      - name: Install Dependencies
        run: |
          if [ -f "Podfile" ]; then
            pod install
          fi

      - name: Build for iOS Device (Without Signing)
        run: |
          xcodebuild -workspace JARVIS.xcworkspace \
                     -scheme JARVIS \
                     -sdk iphoneos \
                     -configuration Release \
                     build

      - name: Build for Simulator (Without Signing)
        run: |
          xcodebuild -workspace JARVIS.xcworkspace \
                     -scheme JARVIS \
                     -sdk iphonesimulator \
                     -configuration Debug \
                     build

      - name: Archive App (For Future Export)
        run: |
          xcodebuild -workspace JARVIS.xcworkspace \
                     -scheme JARVIS \
                     -sdk iphoneos \
                     -configuration Release \
                     archive -archivePath JARVIS.xcarchive

      - name: Export IPA (Without Developer Account)
        run: |
          mkdir -p output
          xcodebuild -exportArchive \
                     -archivePath JARVIS.xcarchive \
                     -exportPath output \
                     -allowProvisioningUpdates

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: JARVIS.ipa
          path: output/
